nbconvert requires mistune
You get a cryptic error message from iptest if mistune is not installed.

Test group: nbconvert
E
======================================================================
ERROR: Failure: AttributeError ('module' object has no attribute 'nbconvert')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/loader.py", line 403, in loadTestsFromName
    module = resolve_name(addr.module)
  File "/usr/lib/python2.7/dist-packages/nose/util.py", line 321, in resolve_name
    obj = getattr(obj, part)
AttributeError: 'module' object has no attribute 'nbconvert'

----------------------------------------------------------------------
Ran 1 test in 0.001s

FAILED (errors=1